name: deploy-non-prd
on:
  push:
    branches:
      - dev
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/main" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/cs-go-skin-shop-int222/frontend:${{ env.ENV_NAME }}
      - name: Anchore Container Scan
        uses: anchore/scan-action@v3.0.0
        with:
          image: "ghcr.io/cs-go-skin-shop-int222/frontend:${{ env.ENV_NAME }}"
          fail-build: false
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/cs-go-skin-shop-int222/frontend:${{ env.ENV_NAME }}'
          target: 'https://blackcarrack.tech/'
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/main" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      - run: echo $GITHUB_ENV
      - name: deploy with Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: ${{ secrets.SSH_HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            docker pull ghcr.io/cs-go-skin-shop-int222/frontend:${{ env.ENV_NAME }}
            docker-compose -f ~/docker-compose/app-compose.yml down
            docker-compose -f ~/docker-compose/app-compose.yml up -d
